// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	participant "vac/features/participant"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AcceptParticipant provides a mock function with given fields: _a0, _a1
func (_m *Service) AcceptParticipant(_a0 int, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApplyParticipant provides a mock function with given fields: _a0
func (_m *Service) ApplyParticipant(_a0 participant.ParticipantCore) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(participant.ParticipantCore) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteParticipant provides a mock function with given fields: _a0
func (_m *Service) DeleteParticipant(_a0 participant.ParticipantCore) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(participant.ParticipantCore) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetParticipantByID provides a mock function with given fields: _a0
func (_m *Service) GetParticipantByID(_a0 int) (participant.ParticipantCore, error) {
	ret := _m.Called(_a0)

	var r0 participant.ParticipantCore
	if rf, ok := ret.Get(0).(func(int) participant.ParticipantCore); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(participant.ParticipantCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParticipantByUserID provides a mock function with given fields: _a0
func (_m *Service) GetParticipantByUserID(_a0 int) ([]participant.ParticipantCore, error) {
	ret := _m.Called(_a0)

	var r0 []participant.ParticipantCore
	if rf, ok := ret.Get(0).(func(int) []participant.ParticipantCore); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]participant.ParticipantCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParticipantByVacID provides a mock function with given fields: _a0
func (_m *Service) GetParticipantByVacID(_a0 int) ([]participant.ParticipantCore, error) {
	ret := _m.Called(_a0)

	var r0 []participant.ParticipantCore
	if rf, ok := ret.Get(0).(func(int) []participant.ParticipantCore); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]participant.ParticipantCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParticipantMultiParam provides a mock function with given fields: _a0, _a1
func (_m *Service) GetParticipantMultiParam(_a0 int, _a1 int) (participant.ParticipantCore, error) {
	ret := _m.Called(_a0, _a1)

	var r0 participant.ParticipantCore
	if rf, ok := ret.Get(0).(func(int, int) participant.ParticipantCore); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(participant.ParticipantCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectParticipant provides a mock function with given fields: _a0, _a1
func (_m *Service) RejectParticipant(_a0 int, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParticipant provides a mock function with given fields: data
func (_m *Service) UpdateParticipant(data participant.ParticipantCore) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(participant.ParticipantCore) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
